name: deeptcr-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.18.*
  - tensorflow=1.15
  - keras=2.2.4
  - llvmlite=0.36.0
  - pip
  - pip:
      - DeepTCR @ git+https://github.com/sidhomj/DeepTCR.git
